spring.application.name=emp-crud

spring.datasource.url=jdbc:mysql://localhost:3306/csepq
spring.datasource.username=root
spring.datasource.password=Farooq@5048

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true